### ISSUE TITLE
Roboto font not found in assets

### ISSUE THREAD

**Issue by tural-ali** [mist-webit/yii2-bootstrap-material-design#1]
Thank you for this awesome theme.
I'm getting this error message in firebug everytime

![hvf6t7u](https://cloud.githubusercontent.com/assets/724507/6636567/c79e573a-c98a-11e4-9859-3c49bedb969e.png)

Please, fix it. 
Thanks in advance

**Comment by mist-webit** [comment]
Thank You for notice! And maybe You should thank https://github.com/FezVrasta/bootstrap-material-design for this theme, i just made an Yii2 assetbundle which is based on that theme. 

See this https://github.com/FezVrasta/bootstrap-material-design/issues/493

I guess we'll have to wait and see what happens.

**Comment by tural-ali** [comment]
He just fixed issue. Please fix it. Thank you

**Comment by mist-webit** [comment]
Remove vendor/bower/bootstrap-material-design folder and run composer update and bower dependency should update itself.

**Comment by tural-ali** [comment]
Thanks. Great!
